### ISSUE TITLE
iOS 13 Broke some tests

### ISSUE THREAD

**Issue by gilserrap** [AdevintaSpain/Sencha#22]
@achernoprudov fixed an issue with tests running on iOS 13 https://github.com/AdevintaSpain/Sencha/pull/20, but we are still having some problems with test failing due to: "Failed to execute block because idling resources below are busy."
I am opening this issue to have somewhere to follow up on any progress made towards fixing it.

**Comment by gilserrap** [comment]
looks like someone is already trying to update EarlGrey to work on iOS 13 https://github.com/google/EarlGrey/tree/ios13fixes
However, on the .podspec file I cannot link against a specific branch of EarlGrey.
I tried to link against this branch in my Main project's Podfile, hoping that since the api hasn't changed, I would be able to overwrite the dependency, and end up with the fixes on that branch, working inside of Sencha, but, as I later found out, EarlGrey Source code is built via some obscure scripts and then uploaded as an attachment to the github release, and that is what you download when you add the EarlGrey dependency. 😵

**Comment by weibel** [comment]
I think people can specify a commit on EarlGrey in their podfile to get the latest ios13 fixes. 
However people who want to continue using EG1, will probably need to maintain their own EG1 fork going forward as the core teams development focus has moved to EG2.

**Comment by gilserrap** [comment]
@weibel I tried specifying a iOS13 support branch for EG dependency on my project's Podfile, so that it would override Sencha's EG version, but tests wouldn't build. TBH I didn't dedicate a lot of time to that option, but it didn't look good, although I'd be down for that option if anybody has sucessfully done it. As of now, I'm running UI tests on iOS12 simulator, and will wait for an official release with iOS13 support, or eventually migrate to EG2.

**Comment by bellebethcooper** [comment]
I've spent some time trying to upgrade to EG 2, but wasn't able to get white-boxing working with any of my custom classes. Has anyone else found a way to do this? Without it most of the tests I already have can't work at all in EG 2.

**Comment by gilserrap** [comment]
@bellebethcooper I saw a doc about white-box testing with EG2.0, doesn't [this](https://github.com/google/EarlGrey/blob/earlgrey2/docs/swift-white-boxing.md) work?

**Comment by bellebethcooper** [comment]
@gilserrap It does, but I can only access UIKit stuff, like the example does. I can't access my own app's classes. I opened an issue on EG in the hopes I'd just misunderstood and they could point me in the right direction, but I haven't had a response.

**Comment by gilserrap** [comment]
So, there has been some progress on the subject, and looks like support for iOS13 has been added to EarlGrey, but, there has been no cocoapods release for that, which, in Sencha's case it's as good as if no release was done; https://github.com/google/EarlGrey/pull/1074
Let's hope that a proper cocoapods release comes soon.

**Comment by weibel** [comment]
There is a release now https://github.com/google/EarlGrey/releases/tag/1.16.0

**Comment by gilserrap** [comment]
I've done a release with version 0.14 that updates EarlGrey, so it should work again on iOS 13 now! ✨
